2023-07-27 18:47:57.550218: I tensorflow/tsl/framework/bfc_allocator.cc:1107] Sum Total of in-use chunks: 12.19GiB
2023-07-27 18:47:57.550228: I tensorflow/tsl/framework/bfc_allocator.cc:1109] Total bytes in pool: 22853976064 memory_limit_: 22853976064 available bytes: 0 curr_region_allocation_bytes_: 45707952128
2023-07-27 18:47:57.550245: I tensorflow/tsl/framework/bfc_allocator.cc:1114] Stats: 
Limit:                     22853976064
InUse:                     13088098048
MaxInUse:                  14903066368
NumAllocs:                        1454
MaxAllocSize:               5547753472
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2023-07-27 18:47:57.550265: W tensorflow/tsl/framework/bfc_allocator.cc:497] ***__***_**______********______**********************************************_______________________
2023-07-27 18:47:57.550302: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at bias_op.cc:272 : RESOURCE_EXHAUSTED: OOM when allocating tensor with shape[128,512,21163] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/media/veneto/data/pythonProjects/CPT/CPTrainer.py", line 174, in <module>
    trainer.train(understanding_dataset, None, val_dataset, None, num_epochs=train_epochs)
  File "/media/veneto/data/pythonProjects/CPT/CPTrainer.py", line 92, in train
    _ = model(inp, tar, training=False, enc_padding_mask=enc_padding_mask, look_ahead_mask=combined_mask,
  File "/home/veneto/anaconda3/envs/transformer/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/media/veneto/data/pythonProjects/CPT/CPTModel.py", line 23, in call
    final_output = self.final_layer_u(dec_output)  # (batch_size, tar_seq_len, target_vocab_size)
  File "/media/veneto/data/pythonProjects/CPT/Transformer.py", line 223, in call
    linear_output = self.linear(x)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Exception encountered when calling layer 'dense_100' (type Dense).

{{function_node __wrapped__BiasAdd_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[128,512,21163] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:BiasAdd] name: 

Call arguments received by layer 'dense_100' (type Dense):
  â€¢ inputs=tf.Tensor(shape=(128, 512, 768), dtype=float32)

Process finished with exit code 1
